FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY OrderService/OrderService.csproj OrderService/
COPY ApplicaicationLayer/*.csproj ApplicaicationLayer/
COPY DomainLayer/*.csproj DomainLayer/
COPY OrderService.Infrastructure/*.csproj OrderService.Infrastructure/

RUN dotnet restore OrderService/OrderService.csproj

COPY . .

WORKDIR /src/OrderService
RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "OrderService.dll"]